export type Question={topic:string;prompt:string;options:string[];answer:number;explanation:string};
export type QuizSet={title:string;subtitle:string;questions:Question[]};
const q=(topic:string,prompt:string,options:string[],answer:number,explanation:string):Question=>({topic,prompt,options,answer,explanation});

export const quizSets:QuizSet[]=[
{title:'Correlation & Capture',subtitle:'Dynamic values and boundaries',questions:[
q('Response headers','A response header contains Location: /orders/7842. Which registration captures /orders/7842 from the next response?',['web_reg_save_param_ex("ParamName=NextUrl", "LB=Location: ", "RB=\\r\\n", "Scope=Headers", LAST);','web_add_header("Location", "{NextUrl}");','lr_save_string("Location: /orders/7842", "NextUrl");','web_reg_save_param_ex("ParamName=NextUrl", "LB=Location: ", "RB=\\r\\n", "Scope=Body", LAST);'],0,'Register before the request and search the response headers between Location: and the line ending.'),
q('JSON correlation','Which function is purpose-built to capture an id from a JSON response?',['web_reg_save_param_json','web_reg_find','web_convert_param','lr_save_string'],0,'web_reg_save_param_json extracts values with a JSONPath expression.'),
q('Ordinal','Several sessionId values exist. How do you capture the last match?',['"Ordinal=All"','"Ordinal=Last"','"SaveOffset=-1"','"NotFound=Warning"'],1,'Ordinal=Last selects the final boundary match.'),
q('Array capture','Which option saves every boundary match into Param_1, Param_2, and Param_count?',['"Ordinal=All"','"Ordinal=0"','"SaveLen=All"','"Scope=All"'],0,'Ordinal=All creates indexed parameters and a count parameter.'),
q('Registration order','Where must a web_reg_save_param_ex call appear?',['After the request that returns the value','Before the request that returns the value','Only inside vuser_end','After lr_end_transaction'],1,'Correlation functions register a rule for the next matching response.'),
q('Boundary safety','A left boundary includes characters such as ?. What prevents interpretation as special characters?',['Use JSONPath','Set Binary=Yes','Escape the characters in the C string where required','Use web_add_auto_header'],2,'C string escaping preserves the intended literal boundary text.'),
q('Not found behavior','Which attribute lets a missing optional value continue with a warning?',['"NotFound=Warning"','"Fail=No"','"Continue=Yes"','"Optional=True"'],0,'NotFound=Warning keeps the step from failing when no match is found.'),
q('Parameter use','How do you insert the captured parameter OrderId into a later URL?',['${OrderId}','%OrderId%','{OrderId}','<OrderId>'],2,'LoadRunner parameter substitution uses braces.'),
q('HTML decoding','A captured value contains &amp;. Which function can decode it for later use?',['web_convert_param','web_reg_find','lr_eval_string','web_cleanup_cookies'],0,'web_convert_param can convert HTML-encoded captured data.'),
q('Debugging','What is the fastest first check when a correlation returns no value?',['Increase think time','Inspect the actual response and verify boundaries/scope','Delete all cookies','Disable transactions'],1,'The real response confirms whether the value, scope, and boundaries still match.')
]},
{title:'Transactions & Flow',subtitle:'Timing and script control',questions:[
q('Transactions','Which pair measures an end-to-end business process?',['lr_start_transaction / lr_end_transaction','web_reg_find / web_url','lr_think_time / lr_output_message','web_set_sockets_option / web_cleanup_cookies'],0,'Start and end the same named transaction around the business steps.'),
q('Status','How do you explicitly fail a transaction when validation fails?',['lr_end_transaction("Pay", LR_FAIL);','lr_abort_transaction("Pay");','lr_error_message("Pay");','return LR_FAIL;'],0,'LR_FAIL records the named transaction as failed.'),
q('Automatic status','Which ending status derives success or failure from errors inside the transaction?',['LR_AUTO','LR_PASS','LR_STOP','LR_DEFAULT'],0,'LR_AUTO uses the errors recorded while the transaction was open.'),
q('Think time','Where should lr_think_time normally be placed?',['Inside the server response body','Between user actions, outside measured response time','Only in vuser_init','Immediately before every correlation'],1,'Think time models user pacing and should not inflate transaction response time.'),
q('Iteration control','Which action section repeats according to the runtime iteration settings?',['vuser_init','Action','vuser_end','globals.h'],1,'Action is the repeatedly executed business workflow.'),
q('Conditional flow','Which expression correctly compares a captured Status parameter with APPROVED?',['if ({Status} == "APPROVED")','if (strcmp(lr_eval_string("{Status}"), "APPROVED") == 0)','if (Status.equals("APPROVED"))','if (lr_compare("Status", "APPROVED"))'],1,'Evaluate the parameter, then use standard C string comparison.'),
q('Nested timing','What happens when transactions are nested?',['The script will never compile','Both can record time, but names and boundaries must be managed carefully','The inner transaction is ignored','The controller removes both'],1,'LoadRunner supports nested timing, though clear boundaries are essential.'),
q('Rendezvous','What does lr_rendezvous("Checkout") do during a load test?',['Clears cache','Synchronizes configured Vusers at a point','Starts a transaction','Connects to the database'],1,'A rendezvous creates a coordinated concurrency spike.'),
q('Pacing','What controls the delay between iterations rather than between steps?',['Think time','Pacing','Connection timeout','Log level'],1,'Pacing controls iteration start frequency.'),
q('Cleanup','Where should a logout that must run once after all iterations normally be placed?',['vuser_init','Action','vuser_end','Extra Files'],2,'vuser_end is intended for one-time teardown logic.')
]},
{title:'Validation & Errors',subtitle:'Checks, failures, and recovery',questions:[
q('Content check','Which function registers a text check on the next response?',['web_reg_find','web_find','lr_find_string','web_reg_save_param'],0,'web_reg_find registers a validation before the request.'),
q('Fail handling','A required confirmation text is absent. Which attribute makes the check fail?',['"Fail=Found"','"Fail=NotFound"','"NotFound=Error"','"Status=Fail"'],1,'Fail=NotFound reports failure when the expected text is missing.'),
q('HTTP errors','Which runtime option is commonly used to continue code execution after an HTTP error so custom recovery can run?',['web_set_max_html_param_len','lr_continue_on_error','web_set_timeout','lr_set_debug_message'],1,'lr_continue_on_error can temporarily allow scripted recovery logic.'),
q('Last error','Which function returns the code for the most recent error?',['lr_get_last_error','web_get_error','lr_error_code','web_get_last_status'],0,'lr_get_last_error exposes the last error code to the script.'),
q('Logging','Which function writes a formatted informational line to the replay log?',['lr_output_message','printf only','web_reg_find','lr_save_string'],0,'lr_output_message is the standard LoadRunner log output function.'),
q('Sensitive data','What is the safest logging practice for authentication tokens?',['Log every token at extended level','Never log secrets; mask identifiers when debugging','Put tokens in transaction names','Print only in vuser_end'],1,'Secrets should not enter logs, results, or shared artifacts.'),
q('HTTP status','How can a script read the last HTTP response code after a web request?',['web_get_int_property(HTTP_INFO_RETURN_CODE)','lr_get_transaction_status','web_get_timeout','atoi("{status}")'],0,'HTTP_INFO_RETURN_CODE returns the latest HTTP status code.'),
q('Custom failure','Which call records a script error with a formatted message?',['lr_error_message','lr_output_message','web_add_header','lr_save_datetime'],0,'lr_error_message reports an error and supports formatting.'),
q('Negative check','How do you fail when an error banner is present?',['web_reg_find with Fail=Found','web_reg_find with Fail=NotFound','web_reg_save_param with Ordinal=All','lr_start_transaction only'],0,'Fail=Found supports negative assertions for unwanted content.'),
q('Robust validation','Which validation is generally strongest?',['Checking only HTTP 200','Checking a business outcome plus status and key data','Checking response length only','Checking replay log color'],1,'Business-level validation catches successful transport with incorrect application behavior.')
]},
{title:'Data & Parameterization',subtitle:'Datasets and unique users',questions:[
q('Data files','Which syntax references a column named Username?',['{Username}','${Username}','%Username%','[Username]'],0,'VuGen replaces brace-delimited parameter names at runtime.'),
q('Update mode','Which setting gives a Vuser a new row on every iteration?',['Update value on Each iteration','Update value Once','Same line as UserId','Sequential once'],0,'Each iteration advances according to the chosen row-selection method.'),
q('Unique data','What must be true when using Unique row selection?',['The data file needs enough rows for the planned Vusers and iterations','Every row must be identical','Think time must be disabled','The file must be JSON'],0,'Insufficient unique rows leads to exhaustion based on the configured behavior.'),
q('Date values','Which function saves a formatted current date/time to a parameter?',['lr_save_datetime','lr_save_string','web_save_timestamp_param','time_format'],0,'lr_save_datetime formats and saves the current time.'),
q('Randomization','Which row-selection method helps vary test data without guaranteeing exclusivity?',['Random','Unique','Sequential','Same line as'],0,'Random selection varies rows but can reuse them.'),
q('Dependent rows','How do you keep Password on the same row selected for Username?',['Configure Password as Same line as Username','Use Ordinal=All','Call lr_eval_string twice','Set both to Random'],0,'Same line as preserves relationships across parameter columns.'),
q('C conversion','Which code converts captured {Quantity} text to an integer?',['atoi(lr_eval_string("{Quantity}"))','int("{Quantity}")','lr_to_int("Quantity")','parseInt({Quantity})'],0,'Evaluate the parameter to a C string, then convert it with atoi.'),
q('Runtime save','Which call stores a computed C string buffer into parameter Result?',['lr_save_string(buffer, "Result")','web_reg_save_param(buffer)','lr_eval_string(buffer)','web_add_header("Result", buffer)'],0,'lr_save_string copies a C string into a LoadRunner parameter.'),
q('Parameter length','Which setting may need increasing for very large correlation values?',['web_set_max_html_param_len','lr_set_transaction_status','web_set_user','web_set_proxy_bypass'],0,'The maximum HTML parameter length limits captured value size.'),
q('Data design','What is best for a test that creates accounts?',['Reuse one username across all Vusers','Provide unique usernames or generate collision-safe values','Hard-code admin credentials','Disable validation'],1,'Unique or safely generated data prevents duplicate-account conflicts.')
]},
{title:'Protocols & Diagnostics',subtitle:'HTTP behavior and troubleshooting',questions:[
q('Request type','Which function is best for a simple GET of a full URL?',['web_url','web_submit_data','web_reg_find','web_custom_request only'],0,'web_url is the straightforward URL-mode GET step.'),
q('REST body','Which function gives direct control of method, headers, and raw request body?',['web_custom_request','web_url','lr_start_transaction','web_cleanup_cookies'],0,'web_custom_request is suited to raw REST payloads and non-GET methods.'),
q('Form submit','Which function commonly sends name/value form fields?',['web_submit_data','web_reg_save_param_json','web_convert_param','lr_save_string'],0,'web_submit_data models form field submissions.'),
q('Headers','What does web_add_auto_header do?',['Adds a header to subsequent requests until removed','Captures a response header','Adds a header to only the previous request','Changes the transaction name'],0,'Automatic headers persist for following requests until explicitly removed.'),
q('Cookies','Which function clears the Vuser cookie jar?',['web_cleanup_cookies','web_remove_auto_header','web_cache_cleanup','lr_cleanup'],0,'web_cleanup_cookies removes stored cookies for the virtual user.'),
q('Caching','Which function clears the simulated browser cache?',['web_cache_cleanup','web_cleanup_cookies','web_set_sockets_option','web_reg_find'],0,'web_cache_cleanup resets cached resources separately from cookies.'),
q('TLS troubleshooting','What should you check first when replay shows certificate failures?',['Certificate trust, hostname, protocol compatibility, and proxy path','Transaction color','Parameter row order','Think-time multiplier'],0,'TLS errors are usually environmental or trust/protocol related.'),
q('Snapshots','What is the main value of replay snapshots?',['Comparing recorded and replayed requests/responses','Generating load directly','Encrypting parameters','Configuring pacing'],0,'Snapshot comparison reveals dynamic values and request differences.'),
q('Logging level','When should extended logging be enabled in a load test?',['For every Vuser for the full test','Only for targeted diagnosis because it adds overhead','Never','Only to improve throughput'],1,'Verbose logging consumes resources and can distort test behavior.'),
q('Performance diagnosis','High response time appears only under load. What is the best next step?',['Correlate transaction timing with server and infrastructure metrics','Add longer think time and stop analysis','Remove all checks','Rerecord every script immediately'],0,'Cross-layer correlation helps identify the actual bottleneck rather than guessing.')
]}
];
