export type Question={topic:string;prompt:string;options:string[];answer:number;explanation:string};
export type QuizSet={title:string;subtitle:string;questions:Question[]};
const q=(topic:string,prompt:string,options:string[],answer:number,explanation:string):Question=>({topic,prompt,options,answer,explanation});

export const quizSets:QuizSet[]=[
{title:'Correlation & Capture',subtitle:'Dynamic values and boundaries',questions:[
q('Response headers','A response header contains Location: /orders/7842. Which registration captures /orders/7842 from the next response?',['web_reg_save_param_ex("ParamName=NextUrl", "LB=Location: ", "RB=\\r\\n", "Scope=Headers", LAST);','web_add_header("Location", "{NextUrl}");','lr_save_string("Location: /orders/7842", "NextUrl");','web_reg_save_param_ex("ParamName=NextUrl", "LB=Location: ", "RB=\\r\\n", "Scope=Body", LAST);'],0,'Register before the request and search the response headers between Location: and the line ending.'),
q('JSON correlation','Which function is purpose-built to capture an id from a JSON response?',['web_reg_save_param_json','web_reg_find','web_convert_param','lr_save_string'],0,'web_reg_save_param_json extracts values with a JSONPath expression.'),
q('Ordinal','Several sessionId values exist. How do you capture the last match?',['"Ordinal=All"','"Ordinal=Last"','"SaveOffset=-1"','"NotFound=Warning"'],1,'Ordinal=Last selects the final boundary match.'),
q('Array capture','Which option saves every boundary match into Param_1, Param_2, and Param_count?',['"Ordinal=All"','"Ordinal=0"','"SaveLen=All"','"Scope=All"'],0,'Ordinal=All creates indexed parameters and a count parameter.'),
q('Registration order','Where must a web_reg_save_param_ex call appear?',['After the request that returns the value','Before the request that returns the value','Only inside vuser_end','After lr_end_transaction'],1,'Correlation functions register a rule for the next matching response.'),
q('Boundary safety','A left boundary includes characters such as ?. What prevents interpretation as special characters?',['Use JSONPath','Set Binary=Yes','Escape the characters in the C string where required','Use web_add_auto_header'],2,'C string escaping preserves the intended literal boundary text.'),
q('Not found behavior','Which attribute lets a missing optional value continue with a warning?',['"NotFound=Warning"','"Fail=No"','"Continue=Yes"','"Optional=True"'],0,'NotFound=Warning keeps the step from failing when no match is found.'),
q('Parameter use','How do you insert the captured parameter OrderId into a later URL?',['${OrderId}','%OrderId%','{OrderId}','<OrderId>'],2,'LoadRunner parameter substitution uses braces.'),
q('HTML decoding','A captured value contains &amp;. Which function can decode it for later use?',['web_convert_param','web_reg_find','lr_eval_string','web_cleanup_cookies'],0,'web_convert_param can convert HTML-encoded captured data.'),
q('Debugging','What is the fastest first check when a correlation returns no value?',['Increase think time','Inspect the actual response and verify boundaries/scope','Delete all cookies','Disable transactions'],1,'The real response confirms whether the value, scope, and boundaries still match.')
]},
{title:'Transactions & Flow',subtitle:'Timing and script control',questions:[
q('Transactions','Which pair measures an end-to-end business process?',['lr_start_transaction / lr_end_transaction','web_reg_find / web_url','lr_think_time / lr_output_message','web_set_sockets_option / web_cleanup_cookies'],0,'Start and end the same named transaction around the business steps.'),
q('Status','How do you explicitly fail a transaction when validation fails?',['lr_end_transaction("Pay", LR_FAIL);','lr_abort_transaction("Pay");','lr_error_message("Pay");','return LR_FAIL;'],0,'LR_FAIL records the named transaction as failed.'),
q('Automatic status','Which ending status derives success or failure from errors inside the transaction?',['LR_AUTO','LR_PASS','LR_STOP','LR_DEFAULT'],0,'LR_AUTO uses the errors recorded while the transaction was open.'),
q('Think time','Where should lr_think_time normally be placed?',['Inside the server response body','Between user actions, outside measured response time','Only in vuser_init','Immediately before every correlation'],1,'Think time models user pacing and should not inflate transaction response time.'),
q('Iteration control','Which action section repeats according to the runtime iteration settings?',['vuser_init','Action','vuser_end','globals.h'],1,'Action is the repeatedly executed business workflow.'),
q('Conditional flow','Which expression correctly compares a captured Status parameter with APPROVED?',['if ({Status} == "APPROVED")','if (strcmp(lr_eval_string("{Status}"), "APPROVED") == 0)','if (Status.equals("APPROVED"))','if (lr_compare("Status", "APPROVED"))'],1,'Evaluate the parameter, then use standard C string comparison.'),
q('Nested timing','What happens when transactions are nested?',['The script will never compile','Both can record time, but names and boundaries must be managed carefully','The inner transaction is ignored','The controller removes both'],1,'LoadRunner supports nested timing, though clear boundaries are essential.'),
q('Rendezvous','What does lr_rendezvous("Checkout") do during a load test?',['Clears cache','Synchronizes configured Vusers at a point','Starts a transaction','Connects to the database'],1,'A rendezvous creates a coordinated concurrency spike.'),
q('Pacing','What controls the delay between iterations rather than between steps?',['Think time','Pacing','Connection timeout','Log level'],1,'Pacing controls iteration start frequency.'),
q('Cleanup','Where should a logout that must run once after all iterations normally be placed?',['vuser_init','Action','vuser_end','Extra Files'],2,'vuser_end is intended for one-time teardown logic.')
]},
{title:'Validation & Errors',subtitle:'Checks, failures, and recovery',questions:[
q('Content check','Which function registers a text check on the next response?',['web_reg_find','web_find','lr_find_string','web_reg_save_param'],0,'web_reg_find registers a validation before the request.'),
q('Fail handling','A required confirmation text is absent. Which attribute makes the check fail?',['"Fail=Found"','"Fail=NotFound"','"NotFound=Error"','"Status=Fail"'],1,'Fail=NotFound reports failure when the expected text is missing.'),
q('HTTP errors','Which runtime option is commonly used to continue code execution after an HTTP error so custom recovery can run?',['web_set_max_html_param_len','lr_continue_on_error','web_set_timeout','lr_set_debug_message'],1,'lr_continue_on_error can temporarily allow scripted recovery logic.'),
q('Last error','Which function returns the code for the most recent error?',['lr_get_last_error','web_get_error','lr_error_code','web_get_last_status'],0,'lr_get_last_error exposes the last error code to the script.'),
q('Logging','Which function writes a formatted informational line to the replay log?',['lr_output_message','printf only','web_reg_find','lr_save_string'],0,'lr_output_message is the standard LoadRunner log output function.'),
q('Sensitive data','What is the safest logging practice for authentication tokens?',['Log every token at extended level','Never log secrets; mask identifiers when debugging','Put tokens in transaction names','Print only in vuser_end'],1,'Secrets should not enter logs, results, or shared artifacts.'),
q('HTTP status','How can a script read the last HTTP response code after a web request?',['web_get_int_property(HTTP_INFO_RETURN_CODE)','lr_get_transaction_status','web_get_timeout','atoi("{status}")'],0,'HTTP_INFO_RETURN_CODE returns the latest HTTP status code.'),
q('Custom failure','Which call records a script error with a formatted message?',['lr_error_message','lr_output_message','web_add_header','lr_save_datetime'],0,'lr_error_message reports an error and supports formatting.'),
q('Negative check','How do you fail when an error banner is present?',['web_reg_find with Fail=Found','web_reg_find with Fail=NotFound','web_reg_save_param with Ordinal=All','lr_start_transaction only'],0,'Fail=Found supports negative assertions for unwanted content.'),
q('Robust validation','Which validation is generally strongest?',['Checking only HTTP 200','Checking a business outcome plus status and key data','Checking response length only','Checking replay log color'],1,'Business-level validation catches successful transport with incorrect application behavior.')
]},
{title:'Data & Parameterization',subtitle:'Datasets and unique users',questions:[
q('Data files','Which syntax references a column named Username?',['{Username}','${Username}','%Username%','[Username]'],0,'VuGen replaces brace-delimited parameter names at runtime.'),
q('Update mode','Which setting gives a Vuser a new row on every iteration?',['Update value on Each iteration','Update value Once','Same line as UserId','Sequential once'],0,'Each iteration advances according to the chosen row-selection method.'),
q('Unique data','What must be true when using Unique row selection?',['The data file needs enough rows for the planned Vusers and iterations','Every row must be identical','Think time must be disabled','The file must be JSON'],0,'Insufficient unique rows leads to exhaustion based on the configured behavior.'),
q('Date values','Which function saves a formatted current date/time to a parameter?',['lr_save_datetime','lr_save_string','web_save_timestamp_param','time_format'],0,'lr_save_datetime formats and saves the current time.'),
q('Randomization','Which row-selection method helps vary test data without guaranteeing exclusivity?',['Random','Unique','Sequential','Same line as'],0,'Random selection varies rows but can reuse them.'),
q('Dependent rows','How do you keep Password on the same row selected for Username?',['Configure Password as Same line as Username','Use Ordinal=All','Call lr_eval_string twice','Set both to Random'],0,'Same line as preserves relationships across parameter columns.'),
q('C conversion','Which code converts captured {Quantity} text to an integer?',['atoi(lr_eval_string("{Quantity}"))','int("{Quantity}")','lr_to_int("Quantity")','parseInt({Quantity})'],0,'Evaluate the parameter to a C string, then convert it with atoi.'),
q('Runtime save','Which call stores a computed C string buffer into parameter Result?',['lr_save_string(buffer, "Result")','web_reg_save_param(buffer)','lr_eval_string(buffer)','web_add_header("Result", buffer)'],0,'lr_save_string copies a C string into a LoadRunner parameter.'),
q('Parameter length','Which setting may need increasing for very large correlation values?',['web_set_max_html_param_len','lr_set_transaction_status','web_set_user','web_set_proxy_bypass'],0,'The maximum HTML parameter length limits captured value size.'),
q('Data design','What is best for a test that creates accounts?',['Reuse one username across all Vusers','Provide unique usernames or generate collision-safe values','Hard-code admin credentials','Disable validation'],1,'Unique or safely generated data prevents duplicate-account conflicts.')
]},
{title:'Protocols & Diagnostics',subtitle:'HTTP behavior and troubleshooting',questions:[
q('Request type','Which function is best for a simple GET of a full URL?',['web_url','web_submit_data','web_reg_find','web_custom_request only'],0,'web_url is the straightforward URL-mode GET step.'),
q('REST body','Which function gives direct control of method, headers, and raw request body?',['web_custom_request','web_url','lr_start_transaction','web_cleanup_cookies'],0,'web_custom_request is suited to raw REST payloads and non-GET methods.'),
q('Form submit','Which function commonly sends name/value form fields?',['web_submit_data','web_reg_save_param_json','web_convert_param','lr_save_string'],0,'web_submit_data models form field submissions.'),
q('Headers','What does web_add_auto_header do?',['Adds a header to subsequent requests until removed','Captures a response header','Adds a header to only the previous request','Changes the transaction name'],0,'Automatic headers persist for following requests until explicitly removed.'),
q('Cookies','Which function clears the Vuser cookie jar?',['web_cleanup_cookies','web_remove_auto_header','web_cache_cleanup','lr_cleanup'],0,'web_cleanup_cookies removes stored cookies for the virtual user.'),
q('Caching','Which function clears the simulated browser cache?',['web_cache_cleanup','web_cleanup_cookies','web_set_sockets_option','web_reg_find'],0,'web_cache_cleanup resets cached resources separately from cookies.'),
q('TLS troubleshooting','What should you check first when replay shows certificate failures?',['Certificate trust, hostname, protocol compatibility, and proxy path','Transaction color','Parameter row order','Think-time multiplier'],0,'TLS errors are usually environmental or trust/protocol related.'),
q('Snapshots','What is the main value of replay snapshots?',['Comparing recorded and replayed requests/responses','Generating load directly','Encrypting parameters','Configuring pacing'],0,'Snapshot comparison reveals dynamic values and request differences.'),
q('Logging level','When should extended logging be enabled in a load test?',['For every Vuser for the full test','Only for targeted diagnosis because it adds overhead','Never','Only to improve throughput'],1,'Verbose logging consumes resources and can distort test behavior.'),
q('Performance diagnosis','High response time appears only under load. What is the best next step?',['Correlate transaction timing with server and infrastructure metrics','Add longer think time and stop analysis','Remove all checks','Rerecord every script immediately'],0,'Cross-layer correlation helps identify the actual bottleneck rather than guessing.')
]},
{title:'Controller Professional',subtitle:'Advanced scenario engineering',questions:[
q('Workload model','A business process must sustain 600 transactions per hour. What should drive the scenario design?',['Only the maximum Vuser count','Arrival rate, iteration duration, pacing, and measured throughput','The number of scripts in the project','The Controller refresh interval'],1,'A defensible workload model connects business volume to arrival rate, concurrency, pacing, and achieved throughput.'),
q('Scheduling','Which schedule is best when user groups must ramp independently?',['A basic schedule for all groups','A real-world schedule with group-specific actions','Run until completion only','A manual rendezvous schedule'],1,'Real-world schedules allow separate start, ramp, duration, and stop actions per group.'),
q('SLA design','What is the strongest transaction SLA definition?',['Average response time under 3 seconds','Percentile response time plus error-rate and throughput criteria','Maximum response time only','No failed Vusers'],1,'Percentile, error, and throughput criteria resist averages hiding poor tail behavior.'),
q('Pacing calculation','An iteration averages 90 seconds and one Vuser must produce 20 iterations/hour. What total cycle time is required?',['90 seconds','120 seconds','180 seconds','300 seconds'],2,'Twenty iterations per hour requires one iteration every 180 seconds, including execution and pacing.'),
q('Rendezvous policy','When is a rendezvous appropriate?',['To model every normal user action','To create a deliberate simultaneous-load event','To replace pacing','To distribute generators'],1,'Rendezvous points are for specific concurrency spikes, not routine workload pacing.'),
q('Runtime settings','Why should production load runs normally disable full extended logging?',['It prevents parameter substitution','It adds generator CPU, disk, and network overhead','It removes think time','It disables HTML reports'],1,'Verbose logging can distort the workload and exhaust generator resources.'),
q('Scenario health','Throughput stops increasing while response time rises as users increase. What does this usually indicate?',['A likely capacity bottleneck or saturation point','A perfect scalability curve','Too much think time only','A Controller display issue'],0,'Flattening throughput with rising latency is a classic saturation signature.'),
q('IP spoofing','When is IP spoofing technically useful?',['When the application or network must see distinct source IPs','For every HTTP test by default','To improve script correlation','To lower response time'],0,'IP spoofing is justified when source-IP behavior, routing, or limits are part of the test objective.'),
q('Collation','Why collate results before analysis in a distributed test?',['To collect generator result data into the scenario result set','To increase load after the run','To recompile scripts','To reset monitors'],0,'Collation gathers distributed raw results so Analysis can process the complete run.'),
q('Run validity','Which evidence best proves the test maintained the intended workload?',['A screenshot of running Vusers','Achieved transaction rate, active Vusers, pacing, and low generator overhead','A green scenario name','The test duration alone'],1,'Workload validity requires evidence that target volume was actually generated without load-injector saturation.')
]},
{title:'LoadRunner Enterprise',subtitle:'LRE orchestration and governance',questions:[
q('Architecture','What is the primary role of an LRE host pool?',['Store VuGen source code only','Provide controlled Controller and load-generator resources','Replace application servers','Generate Analysis PDFs'],1,'Host pools organize the execution resources available to projects and tests.'),
q('Timeslots','Why reserve a timeslot before an LRE test?',['To correlate dynamic values','To guarantee required hosts and resources for the run window','To create transactions','To update browser cache'],1,'Timeslots prevent competing tests from taking the resources needed for a scheduled run.'),
q('Project isolation','What does assigning resources by project help enforce?',['Automatic script correlation','Governance, ownership, and controlled resource access','Faster DNS resolution','Unlimited concurrent runs'],1,'Project boundaries support permissions, accountability, and resource governance.'),
q('Test definition','What should an LRE performance test contain before execution?',['Only a test name','Scripts, workload groups, schedule, monitors, and runtime configuration','Only Analysis templates','Only host credentials'],1,'The test definition combines workload assets and execution settings into a repeatable run.'),
q('Host purpose','A host configured as both Controller and load generator should be used carefully because:',['The roles can compete for CPU, memory, and network resources','It cannot run HTTP scripts','It disables monitoring','It always doubles throughput'],0,'Combining orchestration and load injection can introduce resource contention.'),
q('Version control','What is the best practice when updating a script used by an established LRE test?',['Overwrite it without notes','Version the change and validate runtime compatibility before the scheduled run','Delete previous results','Change all SLAs'],1,'Traceable versions and a pre-run validation reduce unexpected scenario failures.'),
q('Monitoring','Where should credentials for monitored enterprise systems be managed?',['Hard-coded inside each script','In controlled LRE monitor or credential configuration','In transaction names','In public result comments'],1,'Centralized protected configuration avoids leaking infrastructure credentials.'),
q('Parallel demand','Two teams need the same generators at the same time. What should determine allocation?',['Who starts first without notice','Timeslot and resource-governance policy','Alphabetical test name','Script size'],1,'Reservations and governance make shared performance infrastructure predictable.'),
q('Auditability','Which practice improves reproducibility of LRE results?',['Record the exact test configuration, script versions, hosts, and environment window','Rename every transaction after the run','Use random duration','Disable result collation'],0,'A reproducible run needs traceable workload, assets, infrastructure, and timing.'),
q('Failure triage','An LRE run fails to initialize several groups. What should be checked first?',['Host availability, assignments, connectivity, and script initialization logs','Only application response time','Analysis graph colors','The final report title'],0,'Initialization failures usually point to resources, connectivity, permissions, or script setup.')
]},
{title:'Analysis Engineering',subtitle:'Advanced result interpretation',questions:[
q('Percentiles','Why is the 95th percentile more useful than the average for an SLA?',['It exposes tail latency experienced by a meaningful user fraction','It is always lower than the average','It ignores slow responses','It measures generator CPU'],0,'Percentiles reveal the distribution that an average can conceal.'),
q('Correlation','Which graph combination best tests whether load drives latency?',['Running Vusers or throughput merged with transaction response time','Hits per second with report title','Errors with scenario path','Think time with script size'],0,'Overlaying demand and response time shows how latency changes as workload changes.'),
q('Granularity','What is the risk of using a very large graph granularity?',['Short spikes and transient bottlenecks may be averaged away','The test reruns automatically','Transactions become duplicated','Generators disconnect'],0,'Large buckets smooth the data and can hide brief but important events.'),
q('Outliers','Before deleting outliers, an analyst should:',['Investigate timing, errors, logs, and infrastructure evidence','Always remove the slowest 5%','Replace them with the average','Increase graph colors'],0,'Outliers may be real incidents; removal requires a documented technical reason.'),
q('Throughput','Throughput falls while active users remain stable and errors rise. What is the best interpretation?',['The system may be rejecting or failing work under stress','The system is scaling perfectly','Pacing has no effect','Analysis is missing results'],0,'Stable demand with falling completed work and rising errors indicates degraded capacity.'),
q('Transaction breakdown','What can transaction response-time breakdown help distinguish?',['Time spent in network/server components versus client delay','Script author names','Generator license type','Timeslot ownership'],0,'Breakdown views help locate where elapsed time accumulates.'),
q('Comparison','When comparing baseline and current runs, what must be normalized?',['Workload, data, environment, duration, and measurement window','Only graph colors','Only result folder names','Nothing if the script name matches'],0,'A meaningful comparison controls major workload and environment variables.'),
q('Warm-up','Why exclude a documented warm-up interval from steady-state conclusions?',['Caches, pools, and compilation may still be stabilizing','Warm-up has no transactions','It always contains errors','It is generated by Analysis'],0,'Startup behavior can differ materially from stable operating conditions.'),
q('Error overlay','Why merge errors per second with transaction response time?',['To see whether latency changes coincide with failure bursts','To calculate script lines','To add missing users','To reserve hosts'],0,'Temporal alignment supports causal investigation of degradation events.'),
q('Bottleneck claim','What is required before claiming a database bottleneck?',['Aligned database saturation evidence and workload/response degradation','One slow transaction only','A high average without server data','A large result file'],0,'A bottleneck claim needs corroborating resource or wait evidence aligned with impact.')
]},
{title:'Analysis Diagnostics',subtitle:'Advanced graphs and reporting',questions:[
q('Little’s Law','For a stable system, which relationship approximates concurrency?',['Concurrency ≈ throughput × response time','Concurrency ≈ errors ÷ hits','Concurrency ≈ CPU × memory','Concurrency ≈ pacing − think time'],0,'Little’s Law links average concurrency, throughput, and response time in a stable interval.'),
q('Apdex','What does an Apdex score summarize?',['User satisfaction based on satisfied, tolerating, and frustrated response thresholds','Generator memory only','HTTP payload size','Scenario scheduling accuracy'],0,'Apdex translates response-time thresholds into a normalized satisfaction indicator.'),
q('HTTP codes','A surge in HTTP 429 responses indicates:',['Rate limiting or quota enforcement','Successful caching','DNS acceleration','A correlation boundary match'],0,'HTTP 429 means the service is rejecting requests because the allowed rate was exceeded.'),
q('Median vs mean','The mean is much higher than the median. What does that suggest?',['A right-skewed distribution with slow-tail responses','Every response has the same time','No outliers exist','The graph granularity is zero'],0,'A small group of very slow observations pulls the mean upward.'),
q('Network delay','Which evidence supports a network bottleneck?',['Rising network delay, retransmissions or saturation aligned with response degradation','Database CPU alone','A failed content check only','High think time'],0,'Network causation needs network telemetry aligned with the performance event.'),
q('Data segmentation','Why filter results by transaction and time interval?',['To isolate affected workflows and phases instead of blending unlike behavior','To increase test load','To change runtime settings','To recover deleted scripts'],0,'Segmentation prevents healthy transactions or phases from masking a localized problem.'),
q('Error taxonomy','Why group errors by code and message?',['To separate infrastructure, application, data, and script failures','To reduce Vuser count','To calculate pacing automatically','To reserve an LRE host'],0,'Error categories point to different owners and corrective actions.'),
q('Executive report','What belongs in an executive performance summary?',['Objective, workload achieved, SLA outcome, risks, bottlenecks, and recommendation','Every replay log line','All raw request bodies','Only the fastest transaction'],0,'Decision-makers need concise evidence, impact, and actions rather than raw detail.'),
q('Capacity point','How is the practical capacity point usually identified?',['The highest sustainable workload meeting response-time, error, and resource criteria','The maximum configured Vusers regardless of errors','The first successful request','The longest test duration'],0,'Capacity is the sustainable compliant workload, not simply the largest attempted load.'),
q('Repeatability','What strengthens confidence that a regression is real?',['Repeat runs with controlled conditions and a consistent statistically meaningful difference','One isolated spike','A different test duration each time','Removing all failed samples'],0,'Controlled repetition helps distinguish a persistent regression from natural variation.')
]},
{title:'Controller & Generators',subtitle:'Load-generator connectivity',questions:[
q('Connectivity','What must the Controller verify before assigning Vusers to a generator?',['Host reachability, LoadRunner agent status, permissions, and compatible version','Only browser history','Only script line count','Only Analysis installation'],0,'Generator readiness depends on working communications, agents, permissions, and compatibility.'),
q('Ports','A firewall is introduced between Controller and generators. What is required?',['Allow the documented LoadRunner communication paths and configured ports','Open every port','Disable TLS everywhere','Move correlations to vuser_end'],0,'Only the required product communication paths should be opened and validated.'),
q('Capacity','How should Vusers be distributed across generators?',['By measured generator CPU, memory, network, protocol footprint, and headroom','Evenly by generator name only','All on the Controller','Randomly during the run'],0,'Load distribution should follow calibrated resource consumption and reserve headroom.'),
q('Calibration','Why run a generator calibration test?',['To find how many Vusers it can drive without becoming the bottleneck','To tune the application database','To generate SLAs','To change LRE permissions'],0,'Calibration separates load-injector limits from system-under-test limits.'),
q('Overload signal','Which pattern suggests a load generator is overloaded?',['High generator CPU or memory, delayed Vusers, and reduced request generation','High application database CPU only','Low transaction response time','Stable throughput with ample headroom'],0,'An overloaded injector cannot produce the intended workload reliably.'),
q('Agent service','The Controller cannot connect to one Windows generator. What is the best first check?',['LoadRunner Agent service/process, credentials, firewall, and name resolution','Transaction SLA threshold','Analysis percentile settings','Script think time'],0,'Connection failures most often involve the agent, security context, networking, or DNS.'),
q('Clock sync','Why synchronize clocks across Controller, generators, and monitored servers?',['To align events, logs, and metrics during diagnosis','To increase Vuser capacity','To remove correlation','To compress results'],0,'Consistent timestamps are essential for cross-system event correlation.'),
q('Network placement','Why place generators near the intended user network location?',['To model realistic latency, routing, and network constraints','To make all responses local','To bypass security controls','To eliminate monitoring'],0,'Generator placement determines the network path included in measured performance.'),
q('Versioning','What can happen when Controller and generator versions or patches are incompatible?',['Connection, runtime, or protocol failures','Automatic upgrade with no risk','Only report colors change','Transactions become parameters'],0,'Controller and generators should use a supported compatible product level.'),
q('Result transfer','After a run, result collation from one generator fails. What should be preserved?',['The generator result files and logs until transfer can be recovered','Only the Controller screenshot','Only the scenario schedule','Nothing; rerun immediately'],0,'Raw generator artifacts may be needed to recover the complete result set and diagnose transfer failure.')
]},
{title:'Geographic Load Strategy',subtitle:'Cities, regions, and topology',questions:[
q('User proximity','Generators are in Orlando, Detroit, New York, and Los Angeles. Most users are in Florida. Which generator should carry most of that user load?',['Orlando','Detroit','New York','Los Angeles'],0,'Use the Orlando generator for most Florida traffic because it best represents the users’ regional network path and latency.'),
q('Controller location','With generators in several cities, where should the Controller normally be placed?',['In the city with the most users','In a stable management location with reliable low-latency connectivity to all generators','Always beside the application server','On the busiest generator'],1,'The Controller orchestrates the test rather than representing end-user latency. Reliable connectivity, security, and operational access are more important than user proximity.'),
q('Mixed population','Traffic is 60% Florida, 20% Michigan, 10% New York, and 10% California. What is the best distribution?',['25% on every generator','60% Orlando, 20% Detroit, 10% New York, 10% Los Angeles','100% Orlando','40% New York and 60% Los Angeles'],1,'Distribute virtual users according to the business population when the objective is to reproduce real geographic demand.'),
q('Remote application','Users are in Florida, but the application is hosted in Virginia. Where should user-facing load originate?',['Virginia only','Florida, when measuring the Florida user experience','From the Controller host','From whichever generator has the most CPU'],1,'Place load where users are located when end-to-end regional latency is part of the test objective.'),
q('Datacenter test','The objective is server capacity without internet latency. Where should generators be placed?',['Near the application datacenter on a controlled network','Across every user city','On employee laptops','Only behind slow WAN links'],0,'For a server-capacity test, nearby controlled generators isolate application capacity from wide-area network variability.'),
q('Generator health','The Orlando generator reaches 95% CPU while others remain below 30%. What should you do?',['Keep adding Florida users to Orlando','Add or resize Florida-region generators and redistribute the same regional workload','Move all Florida users to Los Angeles without review','Ignore generator CPU'],1,'A saturated generator invalidates workload delivery. Add regional capacity or rebalance without losing the intended network profile.'),
q('Controller traffic','Why should Controller-to-generator traffic be separated conceptually from generator-to-application traffic?',['They serve different purposes and can follow different network paths','They must always use the same port','The Controller generates every business request','There is no difference'],0,'The Controller manages Vusers and results, while generators send application traffic. Each path has different bandwidth, latency, and security needs.'),
q('Cloud regions','Users are split between the US East and US West coasts. Which cloud-generator plan is strongest?',['Use only the cheapest region','Use generators in representative East and West regions with proportional load','Run everything from the Controller','Place all load in Europe'],1,'Representative regional generators preserve coast-to-coast differences in routing and latency.'),
q('Baseline comparison','A new test moves generators from Orlando to Los Angeles. Can its response times be compared directly with the old run?',['Yes, location never affects results','Only after accounting for changed network latency and route','Yes, if Vuser count is unchanged','Only if transaction names change'],1,'Changing generator geography changes the measured network path, so the runs are not directly equivalent without normalization.'),
q('Disaster recovery','The Orlando generator becomes unavailable just before a Florida-focused test. What is the best response?',['Silently move all load to Los Angeles','Use another validated nearby regional generator or document the topology change and its impact','Run from the Controller without checks','Delete the Florida workload'],1,'Use a validated regional substitute when possible. Any topology change must be documented because it can materially affect latency and conclusions.')
]}
];
